In [50]:
import pandas as pd

FILE = "Sample - Superstore Sales.xls"

orders = pd.read_excel(FILE, sheet_name="Orders")
returns = pd.read_excel(FILE, sheet_name="Returns")
users = pd.read_excel(FILE, sheet_name="Users")

In [51]:
#Завдання 1. Завантаження і перший огляд
print(pd.__version__) #версія pandas
print(orders.shape, returns.shape, users.shape) #розмір таблиць
pd.set_option('display.max_columns', None) #налаштування, щоб бачити усі поля
print(orders.head(5)) # перші 5 рядків
print(orders.tail(5)) #останні 5 рядків
print(orders.shape) #розмір orders
print(orders.dtypes) #типи даних полів
print(orders.memory_usage(deep=True).sum()) #скільки мегабайтів пам’яті займає таблиця
print(orders.memory_usage(deep=True).idxmax()) #назва колонки, яка займає найбільше пам'яті

2.2.3
(8399, 21) (572, 2) (8, 2)
   Row ID  Order ID Order Date Order Priority  Order Quantity       Sales  \
0       1         3 2010-10-13            Low               6    261.5400
1      49       293 2012-10-01           High              49  10123.0200
2      50       293 2012-10-01           High              27    244.5700
3      80       483 2011-07-10           High              30   4965.7595
4      85       515 2010-08-28  Not Specified              19    394.2700

   Discount       Ship Mode     Profit  Unit Price  Shipping Cost  \
0      0.04     Regular Air  -213.2500       38.94          35.00
1      0.07  Delivery Truck   457.8100      208.16          68.02
2      0.01     Regular Air    46.7075        8.69           2.99
3      0.08     Regular Air  1198.9710      195.99           3.99
4      0.08     Regular Air    30.9400       21.78           5.94

        Customer Name Province   Region Customer Segment Product Category  \
0  Muhammed MacIntyre  Nunavut  Nunavut   Small Business  Office Supplies
1        Barry French  Nunavut  Nunavut         Consumer  Office Supplies
2        Barry French  Nunavut  Nunavut         Consumer  Office Supplies
3       Clay Rozendal  Nunavut  Nunavut        Corporate       Technology
4      Carlos Soltero  Nunavut  Nunavut         Consumer  Office Supplies

             Product Sub-Category  \
0          Storage & Organization
1                      Appliances
2  Binders and Binder Accessories
3    Telephones and Communication
4                      Appliances

                                        Product Name Product Container  \
0   Eldon Base for stackable storage shelf, platinum         Large Box
1  1.7 Cubic Foot Compact "Cube" Office Refrigera...        Jumbo Drum
2   Cardinal Slant-D® Ring Binder, Heavy Gauge Vinyl         Small Box
3                                               R380         Small Box
4                           Holmes HEPA Air Purifier        Medium Box

   Product Base Margin  Ship Date
0                 0.80 2010-10-20
1                 0.58 2012-10-02
2                 0.39 2012-10-03
3                 0.58 2011-07-12
4                 0.50 2010-08-30
      Row ID  Order ID Order Date Order Priority  Order Quantity      Sales  \
8394    7765     55558 2010-08-09         Medium               8  1294.0400
8395    7766     55558 2010-08-09         Medium              23   392.5700
8396    7906     56550 2011-04-08  Not Specified              37   823.7800
8397    7907     56550 2011-04-08  Not Specified               8   469.8375
8398    7914     56581 2009-02-08           High              20  2026.0100

      Discount       Ship Mode   Profit  Unit Price  Shipping Cost  \
8394      0.05  Delivery Truck -323.180      150.98          66.27
8395      0.04     Regular Air   22.250       17.07           8.13
8396      0.03     Express Air  343.050       22.23           5.08
8397      0.00     Regular Air -159.236       65.99           8.99
8398      0.10     Express Air  580.430      105.98          13.99

        Customer Name Province Region Customer Segment Product Category  \
8394       Mick Brown  Alberta   West         Consumer        Furniture
8395       Mick Brown  Alberta   West         Consumer  Office Supplies
8396     Frank Hawley  Alberta   West      Home Office        Furniture
8397     Frank Hawley  Alberta   West      Home Office       Technology
8398  Grant Donatelli  Alberta   West         Consumer        Furniture

              Product Sub-Category  \
8394                     Bookcases
8395                     Envelopes
8396            Office Furnishings
8397  Telephones and Communication
8398            Office Furnishings

                                           Product Name Product Container  \
8394                        Bush Mission Pointe Library         Jumbo Box
8395  Recycled Interoffice Envelopes with Re-Use-A-S...         Small Box
8396                          Executive Impressions 14"        Small Pack
8397                                    Talkabout T8367         Small Box
8398  Tenex 46" x 60" Computer Anti-Static Chairmat,...        Medium Box

      Product Base Margin  Ship Date
8394                 0.65 2010-08-09
8395                 0.38 2010-08-11
8396                 0.41 2011-04-10
8397                 0.56 2011-04-09
8398                 0.65 2009-02-11
(8399, 21)
Row ID                           int64
Order ID                         int64
Order Date              datetime64[ns]
Order Priority                  object
Order Quantity                   int64
Sales                          float64
Discount                       float64
Ship Mode                       object
Profit                         float64
Unit Price                     float64
Shipping Cost                  float64
Customer Name                   object
Province                        object
Region                          object
Customer Segment                object
Product Category                object
Product Sub-Category            object
Product Name                    object
Product Container               object
Product Base Margin            float64
Ship Date               datetime64[ns]
dtype: object
6000238
Product Name

In [52]:
#Завдання 2. Описова статистика
print(orders.describe(include='number')) #описова статистика для числових полів
print(orders.describe(exclude='number')) #описова статистика для нечислових полів
print(len(orders['Product Category'].unique()), len(orders['Product Sub-Category'].unique()), len(orders['Region'].unique())) # кількість унікальних значень у колонках Product Category, Product Sub-Category і Region
print(round(orders['Ship Mode'].value_counts(normalize=True) * 100, 2)) #частка кожного способу доставки Ship Mode

            Row ID      Order ID  Order Quantity         Sales     Discount  \
count  8399.000000   8399.000000     8399.000000   8399.000000  8399.000000
mean   4200.000000  29965.179783       25.571735   1775.878179     0.049671
std    2424.726789  17260.883447       14.481071   3585.050525     0.031823
min       1.000000      3.000000        1.000000      2.240000     0.000000
25%    2100.500000  15011.500000       13.000000    143.195000     0.020000
50%    4200.000000  29857.000000       26.000000    449.420000     0.050000
75%    6299.500000  44596.000000       38.000000   1709.320000     0.080000
max    8399.000000  59973.000000       50.000000  89061.050000     0.250000

             Profit   Unit Price  Shipping Cost  Product Base Margin
count   8399.000000  8399.000000    8399.000000          8336.000000
mean     181.184422    89.346259      12.838557             0.512513
std     1196.653326   290.354383      17.264052             0.135589
min   -14140.701600     0.990000       0.490000             0.350000
25%      -83.315000     6.480000       3.300000             0.380000
50%       -1.500000    20.990000       6.070000             0.520000
75%      162.748000    85.990000      13.990000             0.590000
max    27220.690000  6783.020000     164.730000             0.850000
                           Order Date Order Priority    Ship Mode  \
count                            8399           8399         8399
unique                            NaN              5            3
top                               NaN           High  Regular Air
freq                              NaN           1768         6270
mean    2010-12-25 00:40:58.578402048            NaN          NaN
min               2009-01-01 00:00:00            NaN          NaN
25%               2009-12-20 00:00:00            NaN          NaN
50%               2010-12-17 00:00:00            NaN          NaN
75%               2012-01-01 12:00:00            NaN          NaN
max               2012-12-30 00:00:00            NaN          NaN

       Customer Name Province Region Customer Segment Product Category  \
count           8399     8399   8399             8399             8399
unique           795       13      8                4                3
top      Darren Budd  Ontario   West        Corporate  Office Supplies
freq              41     1826   1991             3076             4610
mean             NaN      NaN    NaN              NaN              NaN
min              NaN      NaN    NaN              NaN              NaN
25%              NaN      NaN    NaN              NaN              NaN
50%              NaN      NaN    NaN              NaN              NaN
75%              NaN      NaN    NaN              NaN              NaN
max              NaN      NaN    NaN              NaN              NaN

       Product Sub-Category                               Product Name  \
count                  8399                                       8399
unique                   17                                       1263
top                   Paper  Global High-Back Leather Tilter, Burgundy
freq                   1225                                         24
mean                    NaN                                        NaN
min                     NaN                                        NaN
25%                     NaN                                        NaN
50%                     NaN                                        NaN
75%                     NaN                                        NaN
max                     NaN                                        NaN

       Product Container                      Ship Date
count               8399                           8399
unique                 7                            NaN
top            Small Box                            NaN
freq                4347                            NaN
mean                 NaN  2010-12-27 01:28:48.634361088
min                  NaN            2009-01-02 00:00:00
25%                  NaN            2009-12-22 12:00:00
50%                  NaN            2010-12-18 00:00:00
75%                  NaN            2012-01-03 12:00:00
max                  NaN            2012-12-30 00:00:00
3 17 8
Ship Mode
Regular Air       74.65
Delivery Truck    13.64
Express Air       11.70
Name: proportion, dtype: float64

In [53]:
#Завдання 3. Вибірка й індексація
print(orders[['Order ID', 'Sales', 'Profit']].equals(orders.loc[:, ['Order ID', 'Sales', 'Profit']])) #отримайте підтаблицю лише з колонок Order ID, Sales і Profit двома різними способами і переконайтеся, що результати однакові
print(orders.iloc[100:111]) #рядки з позиціями від 100 до 110 включно
print(orders.loc[0:20, 'Profit':'Product Category']) #перші 20 рядків і колонки від Profit до Product Category включно
orders_copy = orders.copy() #робимо копію дф
orders_copy.index = orders_copy['Order ID']#змінюємо індекси на Order ID
print(len(orders_copy.loc[24132]))#кі-ть рядків замовлення 24132
orders_copy.reset_index(drop=True) #скидаємо індекси
print(orders.shape == orders_copy.shape) #розміри таблиці не змінилися

True
     Row ID  Order ID Order Date Order Priority  Order Quantity      Sales  \
100    1544     11137 2012-11-29           High              48  5188.8600
101    1551     11202 2012-03-17         Medium               8   339.8100
102    1589     11456 2010-04-12            Low              15  1519.9000
103    1590     11460 2010-08-24           High              30   102.2400
104    1594     11495 2011-07-04           High               6   965.6900
105    1654     11911 2010-11-10       Critical              25   397.8400
106    1655     11941 2010-06-24       Critical               4    73.0700
107    1656     11941 2010-06-24       Critical              26  4679.1000
108    1675     12096 2012-09-19         Medium              46  8009.5925
109    1676     12096 2012-09-19         Medium              23  4689.6600
110    1710     12289 2011-12-24            Low              25  3019.4100

     Discount       Ship Mode     Profit  Unit Price  Shipping Cost  \
100      0.10     Regular Air   395.1200      111.03           8.64
101      0.05     Regular Air    79.5855       43.41           2.99
102      0.09     Regular Air   399.3700      105.34          24.49
103      0.09     Regular Air    37.7900        3.69           0.50
104      0.00  Delivery Truck  -144.1980      146.34          43.75
105      0.00     Regular Air   -14.7545       15.22           9.73
106      0.08     Regular Air   -41.0100       15.70          11.25
107      0.05  Delivery Truck   111.5200      179.29          29.21
108      0.02     Regular Air  2332.3950      200.99           8.08
109      0.01     Regular Air  2176.1900      194.30          11.54
110      0.04     Regular Air  1269.0500      120.97           7.11

         Customer Name               Province                 Region  \
100   Allen Rosenblatt  Northwest Territories  Northwest Territories
101      Barry Weirich  Northwest Territories  Northwest Territories
102      Doug Bickford  Northwest Territories  Northwest Territories
103       Carl Jackson  Northwest Territories  Northwest Territories
104     Brendan Dodson  Northwest Territories  Northwest Territories
105       Edward Hooks  Northwest Territories  Northwest Territories
106       Jamie Kunitz  Northwest Territories  Northwest Territories
107       Jamie Kunitz  Northwest Territories  Northwest Territories
108  Michelle Lonsdale  Northwest Territories  Northwest Territories
109  Michelle Lonsdale  Northwest Territories  Northwest Territories
110     Brendan Dodson  Northwest Territories  Northwest Territories

    Customer Segment Product Category            Product Sub-Category  \
100   Small Business  Office Supplies          Storage & Organization
101        Corporate  Office Supplies  Binders and Binder Accessories
102        Corporate        Furniture              Office Furnishings
103      Home Office  Office Supplies                          Labels
104        Corporate        Furniture                          Tables
105         Consumer  Office Supplies  Binders and Binder Accessories
106        Corporate  Office Supplies          Storage & Organization
107        Corporate        Furniture                          Tables
108      Home Office       Technology    Telephones and Communication
109      Home Office        Furniture              Office Furnishings
110        Corporate       Technology                 Office Machines

                                          Product Name Product Container  \
100                  Fellowes Recycled Storage Drawers         Small Box
101                   Satellite Sectional Post Binders         Small Box
102  Deflect-o DuraMat Antistatic Studded Beveled M...         Large Box
103                                          Avery 487         Small Box
104  Bevis Round Conference Table Top & Single Colu...         Jumbo Box
105  GBC Twin Loop™ Wire Binding Elements, 9/16" Sp...         Small Box
106                       Hanging Personal Folder File         Small Box
107           Bevis Round Conference Table Top, X-Base         Jumbo Box
108                                               5125         Small Box
109                    Electrix Halogen Magnifier Lamp         Large Box
110  Canon BP1200DH 12-Digit Bubble Jet Printing Ca...        Medium Box

     Product Base Margin  Ship Date
100                 0.78 2012-11-30
101                 0.39 2012-03-18
102                 0.61 2010-04-19
103                 0.38 2010-08-26
104                 0.65 2011-07-05
105                 0.36 2010-11-12
106                 0.60 2010-06-25
107                 0.74 2010-06-25
108                 0.59 2012-09-19
109                 0.59 2012-09-21
110                 0.36 2011-12-28
       Profit  Unit Price  Shipping Cost       Customer Name Province  \
0   -213.2500       38.94          35.00  Muhammed MacIntyre  Nunavut
1    457.8100      208.16          68.02        Barry French  Nunavut
2     46.7075        8.69           2.99        Barry French  Nunavut
3   1198.9710      195.99           3.99       Clay Rozendal  Nunavut
4     30.9400       21.78           5.94      Carlos Soltero  Nunavut
5      4.4300        6.64           4.95      Carlos Soltero  Nunavut
6    -54.0385        7.30           7.72        Carl Jackson  Nunavut
7    127.7000       42.76           6.22        Carl Jackson  Nunavut
8   -695.2600      138.14          35.00      Monica Federle  Nunavut
9   -226.3600        4.98           8.33     Dorothy Badders  Nunavut
10  -166.8500        4.28           6.18     Neola Schneider  Nunavut
11   -14.3300        3.95           2.00     Neola Schneider  Nunavut
12   134.7200       21.78           5.94         Carlos Daly  Nunavut
13   114.4600       47.98           3.61         Carlos Daly  Nunavut
14    -4.7150        5.28           2.99       Claudia Miner  Nunavut
15   782.9100       39.89           3.04     Neola Schneider  Nunavut
16    93.8000       15.74           1.39    Allen Rosenblatt  Nunavut
17   440.7200      100.98          26.22     Sylvia Foulston  Nunavut
18  -481.0410       71.37          69.00     Sylvia Foulston  Nunavut
19   -11.6820       65.99           5.26         Jim Radford  Nunavut
20   313.5780      155.99           8.99         Jim Radford  Nunavut

     Region Customer Segment Product Category
0   Nunavut   Small Business  Office Supplies
1   Nunavut         Consumer  Office Supplies
2   Nunavut         Consumer  Office Supplies
3   Nunavut        Corporate       Technology
4   Nunavut         Consumer  Office Supplies
5   Nunavut         Consumer        Furniture
6   Nunavut        Corporate  Office Supplies
7   Nunavut        Corporate  Office Supplies
8   Nunavut        Corporate  Office Supplies
9   Nunavut      Home Office  Office Supplies
10  Nunavut      Home Office  Office Supplies
11  Nunavut      Home Office  Office Supplies
12  Nunavut      Home Office  Office Supplies
13  Nunavut      Home Office       Technology
14  Nunavut   Small Business  Office Supplies
15  Nunavut      Home Office        Furniture
16  Nunavut   Small Business  Office Supplies
17  Nunavut      Home Office        Furniture
18  Nunavut      Home Office        Furniture
19  Nunavut        Corporate       Technology
20  Nunavut        Corporate       Technology
6
True

In [54]:
#Завдання 4. Фільтрація
print(len(orders[orders['Profit'] < 0])) #усі збиткові записи, де Profit менший за нуль, і виведіть їхню кількість
print(orders[(orders['Product Category'] == 'Technology') & (orders['Sales'] > 100)]) #замовлення категорії Technology із Sales понад 1000
print(orders[orders['Region'].isin(['West', 'Atlantic'])]) #замовлення з регіонів West або Atlantic, не повторюючи умову двічі
print(orders[orders['Discount'].between(0.05, 0.1)]) #замовлення зі знижкою в діапазоні від 0.05 до 0.10 включно
print(orders[orders['Province'].str.startswith('S')]['Province'].unique()) #замовлення, де назва провінції у Province починається на літеру S, і виведіть перелік унікальних провінцій у результаті

4264
      Row ID  Order ID Order Date Order Priority  Order Quantity       Sales  \
3         80       483 2011-07-10           High              30   4965.7595
13       135       868 2012-06-08  Not Specified              31   1474.3300
19       203      1344 2012-04-15            Low              15    834.9040
20       204      1344 2012-04-15            Low              18   2480.9205
24       230      1539 2011-03-09            Low              38    184.9900
...      ...       ...        ...            ...             ...         ...
8384    2083     14883 2011-05-06            Low              47   5126.4180
8387    5167     36772 2010-05-15         Medium              16  12007.0500
8388    5577     39492 2011-04-17  Not Specified              31   5347.9875
8393    7586     54279 2011-07-30           High              41  10071.0900
8397    7907     56550 2011-04-08  Not Specified               8    469.8375

      Discount       Ship Mode    Profit  Unit Price  Shipping Cost  \
3         0.08     Regular Air  1198.971      195.99           3.99
13        0.04     Regular Air   114.460       47.98           3.61
19        0.06     Regular Air   -11.682       65.99           5.26
20        0.01     Regular Air   313.578      155.99           8.99
24        0.05     Regular Air  -144.550        4.89           4.93
...        ...             ...       ...         ...            ...
8384      0.03     Regular Air  1557.639      125.99           2.50
8387      0.09  Delivery Truck  2713.950      808.49          55.30
8388      0.01     Regular Air  1332.441      200.99           4.20
8393      0.10  Delivery Truck  1977.690      264.98          17.86
8397      0.00     Regular Air  -159.236       65.99           8.99

      Customer Name Province   Region Customer Segment Product Category  \
3     Clay Rozendal  Nunavut  Nunavut        Corporate       Technology
13      Carlos Daly  Nunavut  Nunavut      Home Office       Technology
19      Jim Radford  Nunavut  Nunavut        Corporate       Technology
20      Jim Radford  Nunavut  Nunavut        Corporate       Technology
24      Carl Ludwig  Nunavut  Nunavut        Corporate       Technology
...             ...      ...      ...              ...              ...
8384  Jason Fortune  Alberta     West        Corporate       Technology
8387   Frank Hawley  Alberta     West      Home Office       Technology
8388  Jason Fortune  Alberta     West        Corporate       Technology
8393   Harry Greene  Alberta     West        Corporate       Technology
8397   Frank Hawley  Alberta     West      Home Office       Technology

              Product Sub-Category  \
3     Telephones and Communication
13            Computer Peripherals
19    Telephones and Communication
20    Telephones and Communication
24            Computer Peripherals
...                            ...
8384  Telephones and Communication
8387               Office Machines
8388  Telephones and Communication
8393               Office Machines
8397  Telephones and Communication

                                           Product Name Product Container  \
3                                                  R380         Small Box
13    DS/HD IBM Formatted Diskettes, 200/Pack - Staples        Small Pack
19                                                 g520         Small Box
20                                               LX 788         Small Box
24    Maxell 3.5" DS/HD IBM-Formatted Diskettes, 10/...        Small Pack
...                                                 ...               ...
8384                                              i2000         Small Box
8387  Hewlett-Packard Business Color Inkjet 3000 [N,...        Jumbo Drum
8388                                              2160i         Small Box
8393              Panasonic KX-P1131 Dot Matrix Printer        Jumbo Drum
8397                                    Talkabout T8367         Small Box

      Product Base Margin  Ship Date
3                    0.58 2011-07-12
13                   0.71 2012-06-10
19                   0.59 2012-04-22
20                   0.58 2012-04-19
24                   0.66 2011-03-14
...                   ...        ...
8384                 0.60 2011-05-15
8387                 0.40 2010-05-17
8388                 0.59 2011-04-20
8393                 0.58 2011-07-31
8397                 0.56 2011-04-09

[1947 rows x 21 columns]
      Row ID  Order ID Order Date Order Priority  Order Quantity      Sales  \
473     8074     57600 2012-11-11       Critical              44   186.9400
474     8075     57600 2012-11-11       Critical              12   407.2000
475     8124     58055 2011-10-27       Critical              26   208.6000
476     8133     58144 2009-12-16            Low              29   778.3800
477     8136     58150 2010-05-07       Critical              24    60.3600
...      ...       ...        ...            ...             ...        ...
8394    7765     55558 2010-08-09         Medium               8  1294.0400
8395    7766     55558 2010-08-09         Medium              23   392.5700
8396    7906     56550 2011-04-08  Not Specified              37   823.7800
8397    7907     56550 2011-04-08  Not Specified               8   469.8375
8398    7914     56581 2009-02-08           High              20  2026.0100

      Discount       Ship Mode   Profit  Unit Price  Shipping Cost  \
473       0.05     Regular Air   85.810        4.13           0.50
474       0.01     Regular Air   -8.420       30.98          17.08
475       0.00     Regular Air  -56.450        7.38           5.21
476       0.01     Regular Air  257.320       26.38           5.86
477       0.03     Regular Air -119.623        2.16           6.05
...        ...             ...      ...         ...            ...
8394      0.05  Delivery Truck -323.180      150.98          66.27
8395      0.04     Regular Air   22.250       17.07           8.13
8396      0.03     Express Air  343.050       22.23           5.08
8397      0.00     Regular Air -159.236       65.99           8.99
8398      0.10     Express Air  580.430      105.98          13.99

           Customer Name              Province    Region Customer Segment  \
473        Grant Carroll  Prince Edward Island  Atlantic   Small Business
474        Grant Carroll  Prince Edward Island  Atlantic   Small Business
475           Julia West  Prince Edward Island  Atlantic         Consumer
476   Muhammed MacIntyre  Prince Edward Island  Atlantic   Small Business
477      Susan Vittorini  Prince Edward Island  Atlantic        Corporate
...                  ...                   ...       ...              ...
8394          Mick Brown               Alberta      West         Consumer
8395          Mick Brown               Alberta      West         Consumer
8396        Frank Hawley               Alberta      West      Home Office
8397        Frank Hawley               Alberta      West      Home Office
8398     Grant Donatelli               Alberta      West         Consumer

     Product Category            Product Sub-Category  \
473   Office Supplies                          Labels
474   Office Supplies                           Paper
475         Furniture              Office Furnishings
476   Office Supplies                           Paper
477   Office Supplies  Binders and Binder Accessories
...               ...                             ...
8394        Furniture                       Bookcases
8395  Office Supplies                       Envelopes
8396        Furniture              Office Furnishings
8397       Technology    Telephones and Communication
8398        Furniture              Office Furnishings

                                           Product Name Product Container  \
473                                           Avery 506         Small Box
474                                           Xerox 197         Small Box
475      Eldon® Expressions™ Wood Desk Accessories, Oak         Small Box
476                                          Xerox 1935         Small Box
477                  Peel & Stick Add-On Corner Pockets         Small Box
...                                                 ...               ...
8394                        Bush Mission Pointe Library         Jumbo Box
8395  Recycled Interoffice Envelopes with Re-Use-A-S...         Small Box
8396                          Executive Impressions 14"        Small Pack
8397                                    Talkabout T8367         Small Box
8398  Tenex 46" x 60" Computer Anti-Static Chairmat,...        Medium Box

      Product Base Margin  Ship Date
473                  0.39 2012-11-13
474                  0.40 2012-11-13
475                  0.56 2011-10-29
476                  0.39 2009-12-23
477                  0.37 2010-05-07
...                   ...        ...
8394                 0.65 2010-08-09
8395                 0.38 2010-08-11
8396                 0.41 2011-04-10
8397                 0.56 2011-04-09
8398                 0.65 2009-02-11

[3071 rows x 21 columns]
      Row ID  Order ID Order Date Order Priority  Order Quantity       Sales  \
1         49       293 2012-10-01           High              49  10123.0200
3         80       483 2011-07-10           High              30   4965.7595
4         85       515 2010-08-28  Not Specified              19    394.2700
5         86       515 2010-08-28  Not Specified              21    146.6900
7         98       613 2011-06-17           High              22    905.0800
...      ...       ...        ...            ...             ...         ...
8389    6492     46212 2012-09-12  Not Specified              43    322.4700
8391    6657     47360 2010-10-08  Not Specified              25   2200.6400
8393    7586     54279 2011-07-30           High              41  10071.0900
8394    7765     55558 2010-08-09         Medium               8   1294.0400
8398    7914     56581 2009-02-08           High              20   2026.0100

      Discount       Ship Mode    Profit  Unit Price  Shipping Cost  \
1         0.07  Delivery Truck   457.810      208.16          68.02
3         0.08     Regular Air  1198.971      195.99           3.99
4         0.08     Regular Air    30.940       21.78           5.94
5         0.05     Regular Air     4.430        6.64           4.95
7         0.09     Regular Air   127.700       42.76           6.22
...        ...             ...       ...         ...            ...
8389      0.09     Express Air    72.280        7.78           2.50
8391      0.05  Delivery Truck  -514.180       89.99          42.00
8393      0.10  Delivery Truck  1977.690      264.98          17.86
8394      0.05  Delivery Truck  -323.180      150.98          66.27
8398      0.10     Express Air   580.430      105.98          13.99

        Customer Name Province   Region Customer Segment Product Category  \
1        Barry French  Nunavut  Nunavut         Consumer  Office Supplies
3       Clay Rozendal  Nunavut  Nunavut        Corporate       Technology
4      Carlos Soltero  Nunavut  Nunavut         Consumer  Office Supplies
5      Carlos Soltero  Nunavut  Nunavut         Consumer        Furniture
7        Carl Jackson  Nunavut  Nunavut        Corporate  Office Supplies
...               ...      ...      ...              ...              ...
8389  Grant Donatelli  Alberta     West         Consumer  Office Supplies
8391     Frank Hawley  Alberta     West      Home Office        Furniture
8393     Harry Greene  Alberta     West        Corporate       Technology
8394       Mick Brown  Alberta     West         Consumer        Furniture
8398  Grant Donatelli  Alberta     West         Consumer        Furniture

              Product Sub-Category  \
1                       Appliances
3     Telephones and Communication
4                       Appliances
5               Office Furnishings
7           Storage & Organization
...                            ...
8389                     Envelopes
8391            Chairs & Chairmats
8393               Office Machines
8394                     Bookcases
8398            Office Furnishings

                                           Product Name Product Container  \
1     1.7 Cubic Foot Compact "Cube" Office Refrigera...        Jumbo Drum
3                                                  R380         Small Box
4                              Holmes HEPA Air Purifier        Medium Box
5     G.E. Longer-Life Indoor Recessed Floodlight Bulbs        Small Pack
7               SAFCO Mobile Desk Side File, Wire Frame         Small Box
...                                                 ...               ...
8389                      Staples #10 Colored Envelopes         Small Box
8391                   Global Leather Task Chair, Black        Jumbo Drum
8393              Panasonic KX-P1131 Dot Matrix Printer        Jumbo Drum
8394                        Bush Mission Pointe Library         Jumbo Box
8398  Tenex 46" x 60" Computer Anti-Static Chairmat,...        Medium Box

      Product Base Margin  Ship Date
1                    0.58 2012-10-02
3                    0.58 2011-07-12
4                    0.50 2010-08-30
5                    0.37 2010-08-30
7                     NaN 2011-06-18
...                   ...        ...
8389                 0.38 2012-09-14
8391                 0.66 2010-10-10
8393                 0.58 2011-07-31
8394                 0.65 2010-08-09
8398                 0.65 2009-02-11

[4518 rows x 21 columns]
['Saskachewan']

In [55]:
#Завдання 5. Пропуски, дублікати та типи даних
na = orders.isna().sum() #кількість порожніх значень у кожній колонці
print(na[na > 0].index[0]) #колонки, де пропуски справді є
orders_copy_2 = orders.copy() #копія ДФ
orders_copy_2['Product Base Margin'].fillna(orders_copy_2['Product Base Margin'].mode()[0], inplace=True) # заповнюємо пропуски найчастішим значенням
print(orders_copy_2['Product Base Margin'].mode()[0]) #виводимо моду по Product Base Margin
orders_copy_3 = orders.dropna(subset='Product Base Margin') #копія orders з видаленими пустими значеннями
print(len(orders), len(orders_copy_3)) #ількість рядків до і після видалення
print(orders.duplicated().sum()) #кількість повністю однакових рядків
print(orders.duplicated(subset=['Order ID', 'Product Name']).sum()) #кількість рядків, що повторюються за парою Order ID + Product Name
order_id_copy = orders['Order ID'].astype('str') #Order ID на текстовий тип
discount_copy = orders['Discount'].astype('float32') #Discount на float32
print(orders['Order ID'].memory_usage(deep=True), order_id_copy.memory_usage(deep=True)) #виводимо обсяг пам’яті до і після перетворення
print(orders['Discount'].memory_usage(deep=True), discount_copy.memory_usage(deep=True)) #виводимо обсяг пам’яті до і після перетворення

Product Base Margin
0.37
8399 8336
0
2
67324 452118
67324 33728

/tmp/ipykernel_719/1780249116.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  orders_copy_2['Product Base Margin'].fillna(orders_copy_2['Product Base Margin'].mode()[0], inplace=True) # заповнюємо пропуски найчастішим значенням

In [56]:
#Завдання 6. Робота з текстом
orders_copy_4 = orders.copy() #копія ДФ
orders_copy_4['First Name'] = orders_copy_4['Customer Name'].str.split(' ', n=1, expand=True).iloc[:,0] #ділимо Customer Name та беремо 1 поле
orders_copy_4['Last Name'] = orders_copy_4['Customer Name'].str.split(' ', n=1, expand=True).iloc[:,1] #ділимо Customer Name та беремо 2 поле
print(orders_copy_4['Last Name'].isna().sum()) #перевіряємо ну пусті значення
orders_copy_4['Name Length'] = orders_copy_4['Product Name'].str.len() #довжина назви товару в символах
print(orders_copy_4['Name Length'].min(), orders_copy_4['Name Length'].max()) #найкоротша й найдовша довжина
print(orders_copy_4['Product Name'].str.contains('Chair', case=False).sum()) #скільки рядків містять у назві товару слово Chair
orders_copy_4['Province'] = orders_copy_4['Province'].str.replace('Saskachewan', 'Saskatchewan') #Saskachewan міняємо на Saskatchewan
orders_copy_4['Product Sub-Category'] = orders_copy_4['Product Sub-Category'].str.replace('&', 'and', regex=False) #символ & на слово and
print(orders_copy_4['Province'].unique()) # унікальні значення Province
print(orders_copy_4['Product Sub-Category'].unique()) #унікальні значення Product Sub-Category

0
3 98
448
['Nunavut' 'Northwest Territories' 'Prince Edward Island' 'Manitoba'
 'British Columbia' 'Nova Scotia' 'Ontario' 'Newfoundland' 'Quebec'
 'New Brunswick' 'Saskatchewan' 'Yukon' 'Alberta']
['Storage and Organization' 'Appliances' 'Binders and Binder Accessories'
 'Telephones and Communication' 'Office Furnishings' 'Paper'
 'Rubber Bands' 'Computer Peripherals' 'Envelopes' 'Bookcases' 'Tables'
 'Labels' 'Pens and Art Supplies' 'Copiers and Fax' 'Chairs and Chairmats'
 'Scissors, Rulers and Trimmers' 'Office Machines']

In [57]:
#Завдання 7. Дати й час
print(orders['Order Date'].dtype, orders['Ship Date'].dtype)
orders_copy_5 = orders.copy() #копія ДФ
orders_copy_5['Order Year'] = orders_copy_5['Order Date'].dt.year #визначаємо поле Order Year
orders_copy_5['Order Month'] = orders_copy_5['Order Date'].dt.month #визначаємо поле Order Month
orders_copy_5['Order Weekday'] = orders_copy_5['Order Date'].dt.day_name #визначаємо поле Order Weekday
orders_copy_5['Order Quarter'] = orders_copy_5['Order Date'].dt.quarter #визначаємо поле Order Quarter
print(orders_copy_5.groupby('Order Year')['Order ID'].count()) #кількість замовлень за кожним роком
orders_copy_5['Ship Delay'] = orders_copy_5['Ship Date'] - orders_copy_5['Order Date'] #
orders_copy_5['Ship Delay'] = orders_copy_5['Ship Delay'].dt.days #кільки днів минуло між замовленням і відвантаженням
print(orders_copy_5['Ship Delay'].min(), orders_copy_5['Ship Delay'].max(), orders_copy_5['Ship Delay'].mean()) # мінімум, максимум і середнє
orders_copy_rsm = orders_copy_5[['Sales', 'Order Date']].set_index('Order Date') #новий дф з індексом Order Date
orders_copy_rsm = orders_copy_rsm.resample('ME').sum() #помісячний ряд сумарних продажів: індекс — кінець місяця
print(len(orders_copy_rsm)) #кількість точок у ряді
orders_copy_rsd = orders_copy_5[['Ship Delay', 'Order Date']].set_index('Order Date') #новий дф з індексом Order Date
orders_copy_rsd.resample('D').mean() #середня затримка відвантаження за кожним днем тижня замовлення

datetime64[ns] datetime64[ns]
Order Year
2009    2153
2010    2142
2011    2002
2012    2102
Name: Order ID, dtype: int64
0 92 2.0332182402666983
48

            Ship Delay
Order Date
2009-01-01    1.500000
2009-01-02    2.166667
2009-01-03    2.400000
2009-01-04    1.333333
2009-01-05    1.266667
...                ...
2012-12-26    1.000000
2012-12-27    1.571429
2012-12-28    1.333333
2012-12-29    0.666667
2012-12-30    0.000000

[1460 rows x 1 columns]

In [58]:
#Завдання 8. Похідні колонки
orders_copy_5.assign(
    Profit_Margin = orders_copy_5['Profit'] / orders_copy_5['Sales'],
    Revenue_Per_Unit = orders_copy_5['Sales'] / orders_copy_5['Order Quantity'],
    Is_Profitable =  orders_copy_5['Profit'] > 0
) #додаємо колонки одним виразом
orders_copy_5['Discount Level'] = orders_copy_5['Discount'].apply(lambda x: 'No' if x == 0  else 'Low' if x < 0.05 else 'High') # додаємо Discount Level через apply
orders_copy_5['Discount Level_'] = pd.cut(orders_copy_5['Discount'], bins=[-1, 0, 0.04, 1], labels=['No', 'Low', 'High']) # додаємо Discount Level_ через pd.cut
print((orders_copy_5['Discount Level'] != orders_copy_5['Discount Level_']).sum()) #перевіряємо на рівність значень
orders_copy_5.drop('Discount Level_', inplace=True, axis=1) #видаляємо дублюючу колонку Discount Level_
mappings = {'West':'W', 'Atlantic':'A', 'Ontario':'ON', 'Quebec':'QC', 'Prarie':'PRA', 'Nunavut':'NU', 'Northwest Territories': 'NWT', 'Yukon':'YT'} #словник для map
orders_copy_5['Region Code'] = orders_copy_5['Region'].map(mappings) # map по словнику
print(orders_copy_5['Region Code'].isna().sum()) #перевірка та пусті значення
orders_copy_5['Delivery Speed'] = orders_copy_5['Ship Delay'].apply(lambda x: 'швидке' if x <= 2 else 'звичайне' if x <= 5 else 'повільне') #Delivery Speed через apply
print(orders_copy_5.groupby(['Delivery Speed'])['Delivery Speed'].count()) #кількість записів у кожній категорії

0
0
Delivery Speed
звичайне    1065
повільне     468
швидке      6866
Name: Delivery Speed, dtype: int64

In [59]:
#Завдання 9. Сортування та ранжування
print(orders['Sales'].sort_values(ascending=False).iloc[0]) #сортування за Sales за спаданням, вибираємо найбільше значення продажів
orders.sort_values(['Region', 'Profit'], ascending=[True, False]) #сортування за двома ключами одночасно: Region за зростанням, Profit за спаданням
print(orders.nlargest(10, ['Profit'])) #10 найприбутковіших записів
print(orders.nsmallest(10, ['Profit'])) #10 найзбитковіших записів
orders_copy_5['Sales Rank'] = orders_copy_5.groupby('Region')['Sales'].rank(method='min', ascending=False) #поле Sales Rank
print(orders_copy_5[(orders_copy_5['Region'] == 'West') & (orders_copy_5['Sales Rank'] == 1)]) #запис із рангом 1 для регіону West

89061.05
      Row ID  Order ID Order Date Order Priority  Order Quantity     Sales  \
4674    4190     29766 2009-03-21         Medium              13  89061.05
5609    1316      9637 2009-01-03            Low              49  28359.40
4767    2909     20967 2011-03-15           High              50  28664.52
6995    4629     32932 2010-01-09            Low              49  29884.60
7906    4096     29187 2009-07-31            Low              35  26095.13
8268    4170     29569 2011-07-03           High              46  27720.98
3648    3698     26432 2009-12-30            Low              48  27820.34
5646    4873     34663 2011-07-06  Not Specified              38  29186.49
3525     567      3841 2009-10-04  Not Specified              20  25409.63
175     2624     19010 2009-06-07            Low              18  23792.93

      Discount       Ship Mode      Profit  Unit Price  Shipping Cost  \
4674      0.00     Regular Air  27220.6900     6783.02          24.49
5609      0.05     Regular Air  14440.3900      574.74          24.49
4767      0.09     Regular Air  13340.2600      599.99          24.49
6995      0.05     Regular Air  12748.8600      599.99          24.49
7906      0.03  Delivery Truck  12606.8100      808.49          55.30
8268      0.07     Regular Air  11984.3950      599.99          24.49
3648      0.08     Regular Air  11630.1460      599.99          24.49
5646      0.05  Delivery Truck  11562.0800      808.49          55.30
3525      0.02     Regular Air  11535.2820     1270.99          19.99
175       0.00     Regular Air  10951.3065     1270.99          19.99

          Customer Name               Province                 Region  \
4674         Emily Phan          New Brunswick               Atlantic
5609        Andy Reiter            Saskachewan                 Prarie
4767  Deborah Brumfield               Manitoba                 Prarie
6995     Karen Carlisle       British Columbia                   West
7906        Rick Wilson                Alberta                   West
8268       Raymond Book                Alberta                   West
3648   Logan Haushalter                 Quebec                 Quebec
5646      Nick Crebassa            Saskachewan                 Prarie
3525     John Stevenson                 Quebec                 Quebec
175       Grant Carroll  Northwest Territories  Northwest Territories

     Customer Segment Product Category            Product Sub-Category  \
4674         Consumer       Technology                 Office Machines
5609        Corporate       Technology                 Office Machines
4767   Small Business       Technology                 Copiers and Fax
6995        Corporate       Technology                 Copiers and Fax
7906         Consumer       Technology                 Office Machines
8268         Consumer       Technology                 Copiers and Fax
3648        Corporate       Technology                 Copiers and Fax
5646        Corporate       Technology                 Office Machines
3525   Small Business  Office Supplies  Binders and Binder Accessories
175    Small Business  Office Supplies  Binders and Binder Accessories

                                           Product Name Product Container  \
4674   Polycom ViewStation™ ISDN Videoconferencing Unit         Large Box
5609  Polycom ViaVideo™ Desktop Video Communications...         Large Box
4767               Hewlett Packard LaserJet 3310 Copier         Large Box
6995                      Canon Image Class D660 Copier         Large Box
7906  Hewlett-Packard Business Color Inkjet 3000 [N,...        Jumbo Drum
8268               Hewlett Packard LaserJet 3310 Copier         Large Box
3648               Hewlett Packard LaserJet 3310 Copier         Large Box
5646  Hewlett-Packard Business Color Inkjet 3000 [N,...        Jumbo Drum
3525  Fellowes PB500 Electric Punch Plastic Comb Bin...         Small Box
175   Fellowes PB500 Electric Punch Plastic Comb Bin...         Small Box

      Product Base Margin  Ship Date
4674                 0.39 2009-03-22
5609                 0.37 2009-01-10
4767                 0.37 2011-03-15
6995                 0.44 2010-01-13
7906                 0.40 2009-08-07
8268                 0.37 2011-07-04
3648                 0.37 2010-01-08
5646                 0.40 2011-07-08
3525                 0.35 2009-10-06
175                  0.35 2009-06-09
      Row ID  Order ID Order Date Order Priority  Order Quantity     Sales  \
8313    5213     37095 2009-03-10            Low               3  18888.00
7677    6076     43044 2009-10-17         Medium               3  19707.20
7968    7223     51553 2011-11-27  Not Specified               3  21366.51
5913    6086     43110 2011-02-06           High               1   3457.99
4661    3198     22917 2009-03-01         Medium               1   3550.28
200     3284     23488 2009-01-06       Critical              30  26133.39
7571    3048     21862 2010-09-12  Not Specified               4  19014.24
3493    8368     59781 2012-12-12  Not Specified              28  24391.16
6920    3575     25476 2012-10-02  Not Specified               4  13698.96
6946    3917     27936 2011-07-07           High               3   9172.32

      Discount       Ship Mode      Profit  Unit Price  Shipping Cost  \
8313      0.09     Regular Air -14140.7016     6783.02          24.49
7677      0.04     Regular Air -12557.9976     6783.02          24.49
7968      0.00     Regular Air -11984.3979     6783.02          24.49
5913      0.05     Regular Air -11861.4600     3499.99          24.49
4661      0.06     Express Air -11769.1700     3499.99          24.49
200       0.04  Delivery Truck -11053.6000      880.98          44.55
7571      0.06     Regular Air -10263.6597     6783.02          24.49
3493      0.04  Delivery Truck  -9611.9100      880.98          44.55
6920      0.05     Regular Air  -9078.9400     3499.99          24.49
6946      0.06  Delivery Truck  -8570.4483     3502.14           8.73

         Customer Name               Province                 Region  \
8313          Roy Phan                Alberta                   West
7677    Laurel Workman                Alberta                   West
7968     Adrian Barton                Alberta                   West
5913  Maxwell Schwartz            Saskachewan                 Prarie
4661      Nathan Mautz          New Brunswick               Atlantic
200         Julia West  Northwest Territories  Northwest Territories
7571       Roger Demir                Alberta                   West
3493     Julia Barnett                 Quebec                 Quebec
6920       Cyra Reiten                  Yukon                  Yukon
6946      Irene Maddox                  Yukon                  Yukon

     Customer Segment Product Category Product Sub-Category  \
8313         Consumer       Technology      Office Machines
7677      Home Office       Technology      Office Machines
7968   Small Business       Technology      Office Machines
5913        Corporate       Technology      Copiers and Fax
4661        Corporate       Technology      Copiers and Fax
200       Home Office        Furniture            Bookcases
7571         Consumer       Technology      Office Machines
3493        Corporate        Furniture            Bookcases
6920         Consumer       Technology      Copiers and Fax
6946         Consumer       Technology      Office Machines

                                           Product Name Product Container  \
8313   Polycom ViewStation™ ISDN Videoconferencing Unit         Large Box
7677   Polycom ViewStation™ ISDN Videoconferencing Unit         Large Box
7968   Polycom ViewStation™ ISDN Videoconferencing Unit         Large Box
5913              Canon imageCLASS 2200 Advanced Copier         Large Box
4661              Canon imageCLASS 2200 Advanced Copier         Large Box
200   Riverside Palais Royal Lawyers Bookcase, Royal...         Jumbo Box
7571   Polycom ViewStation™ ISDN Videoconferencing Unit         Large Box
3493  Riverside Palais Royal Lawyers Bookcase, Royal...         Jumbo Box
6920              Canon imageCLASS 2200 Advanced Copier         Large Box
6946  Okidata Pacemark 4410N Wide Format Dot Matrix ...         Jumbo Box

      Product Base Margin  Ship Date
8313                 0.39 2009-03-14
7677                 0.39 2009-10-19
7968                 0.39 2011-11-28
5913                 0.37 2011-02-08
4661                 0.37 2009-03-04
200                  0.62 2009-01-07
7571                 0.39 2010-09-14
3493                 0.62 2012-12-13
6920                 0.37 2012-10-03
6946                 0.57 2011-07-09
      Row ID  Order ID Order Date Order Priority  Order Quantity    Sales  \
6995    4629     32932 2010-01-09            Low              49  29884.6

      Discount    Ship Mode    Profit  Unit Price  Shipping Cost  \
6995      0.05  Regular Air  12748.86      599.99          24.49

       Customer Name          Province Region Customer Segment  \
6995  Karen Carlisle  British Columbia   West        Corporate

     Product Category Product Sub-Category                   Product Name  \
6995       Technology      Copiers and Fax  Canon Image Class D660 Copier

     Product Container  Product Base Margin  Ship Date  Order Year  \
6995         Large Box                 0.44 2010-01-13        2010

      Order Month                                      Order Weekday  \
6995            1  <bound method PandasDelegate._add_delegate_acc...

      Order Quarter  Ship Delay Discount Level Region Code Delivery Speed  \
6995              1           4           High           W       звичайне

      Sales Rank
6995         1.0

In [60]:
#Завдання 10. Групування та агрегація
print(orders.groupby('Product Category').agg({'Sales': 'sum', 'Profit': 'sum'})) #сумарні Sales і Profit за кожною Product Category
print(orders.groupby('Region').agg(total_sales=('Sales', 'sum'), avg_discount=('Discount', 'mean'), orders_count=('Order ID', 'nunique'), max_profit=('Profit', 'max'))) #чотири показники через agg
orders_prcat = orders.groupby(['Product Category', 'Product Sub-Category'])['Profit'].sum() #сумарний прибуток за кожною парою Product Category + Product Sub-Categor
print(orders_prcat) #виводимо orders_prcat
orders_copy_5['Category Avg Sales']  =  orders_copy_5.groupby('Product Category')['Sales'].transform('mean') #поле Category Avg Sales
orders_copy_5['Sales Deviation'] = orders_copy_5['Sales'] - orders_copy_5['Category Avg Sales'] #поле Sales Deviation'
pvt = pd.pivot_table(orders, values='Profit', index='Product Sub-Category', columns='Product Category', aggfunc='sum') #робимо pivot
print(pvt.idxmax()) # підкатегорії з найбільшим сумарним прибутком

                        Sales         Profit
Product Category
Furniture         5178590.542  117432.986281
Office Supplies   3752762.100  518021.458000
Technology        5984248.182  886313.515300
                        total_sales  avg_discount  orders_count  max_profit
Region
Atlantic               2.014248e+06      0.050713           748  27220.6900
Northwest Territories  8.008473e+05      0.050076           269  10951.3065
Nunavut                1.163765e+05      0.052278            56   3424.2200
Ontario                3.063212e+06      0.049146          1235   9791.0410
Prarie                 2.837305e+06      0.049936          1148  14440.3900
Quebec                 1.510195e+06      0.049808           587  11630.1460
West                   3.597549e+06      0.048815          1330  12748.8600
Yukon                  9.758674e+05      0.050812           396   8734.8800
Product Category  Product Sub-Category
Furniture         Bookcases                         -33582.133500
                  Chairs & Chairmats                149649.725000
                  Office Furnishings                100427.924000
                  Tables                            -99062.529219
Office Supplies   Appliances                         97158.060000
                  Binders and Binder Accessories    307413.418000
                  Envelopes                          48182.600000
                  Labels                             13677.170000
                  Paper                              45263.200000
                  Pens & Art Supplies                 7564.780000
                  Rubber Bands                        -102.670000
                  Scissors, Rulers and Trimmers      -7799.250000
                  Storage & Organization              6664.150000
Technology        Computer Peripherals               94287.480000
                  Copiers and Fax                   167361.464000
                  Office Machines                   307712.930300
                  Telephones and Communication      316951.641000
Name: Profit, dtype: float64
Product Category
Furniture                      Chairs & Chairmats
Office Supplies    Binders and Binder Accessories
Technology           Telephones and Communication
dtype: object

In [61]:
#Завдання 11. Зведені таблиці та зміна форми
print(pd.pivot_table(orders, values='Sales', index='Region', columns='Product Category', aggfunc='sum', margins=True)) #зведена таблицю сумарних продажів
print(pd.crosstab(orders['Customer Segment'], orders['Ship Mode'])) #таблиця спряженості кількості записів
#по 11.3 не зрозумів, що треба зробити

Product Category         Furniture  Office Supplies    Technology  \
Region
Atlantic                708726.782        478464.42  8.270570e+05
Northwest Territories   282837.908        216848.93  3.011605e+05
Nunavut                  43545.614         38615.47  3.421540e+04
Ontario                1109617.500        927431.25  1.026164e+06
Prarie                  919191.126        720090.43  1.198023e+06
Quebec                  605784.144        351822.68  5.525883e+05
West                   1172989.394        797510.76  1.627049e+06
Yukon                   335898.074        221978.16  4.179911e+05
All                    5178590.542       3752762.10  5.984248e+06

Product Category                All
Region
Atlantic               2.014248e+06
Northwest Territories  8.008473e+05
Nunavut                1.163765e+05
Ontario                3.063212e+06
Prarie                 2.837305e+06
Quebec                 1.510195e+06
West                   3.597549e+06
Yukon                  9.758674e+05
All                    1.491560e+07
Ship Mode         Delivery Truck  Express Air  Regular Air
Customer Segment
Consumer                     230          192         1227
Corporate                    421          362         2293
Home Office                  266          235         1531
Small Business               229          194         1219

In [62]:
#Завдання 12. Об’єднання таблиць
orders_mrg_returns = pd.merge(orders, returns, on='Order ID', how='left') #робимо merge
orders_mrg_returns['Status'] = orders_mrg_returns['Status'].fillna('No') #застосовуємо fillna
print(len(orders_mrg_returns)) #к-ть рядків
print(orders_mrg_returns['Status'].value_counts()) #розподіл значень поля Status
print(users['Region'].unique(), orders['Region'].unique()) #значення поля Region у users
print(users['Region'].value_counts()) #розподіл значень поля Region у users
orders_mrg_users_1 = pd.merge(orders, users, on='Region', how='left') #об'єднання до видалення повторів
users_copy = users.drop_duplicates(subset='Region', keep='last') #копія users без повторів
orders_mrg_users_2 = pd.merge(orders, users_copy, on='Region', how='left') #об'єднання після видалення повторів
print(len(orders_mrg_users_1), len(orders_mrg_users_2)) #кількість рядків результату
print(orders_mrg_users_1['Manager'].notna().sum(), orders_mrg_users_2['Manager'].notna().sum()) # кількість записів, які отримали менеджера
df_1= pd.DataFrame({'id': [1, 2, 3], 'name': ['a', 'b', 'c']}) #перший дф
df_2= pd.DataFrame({'id': [1, 4, 5], 'name_d': ['aa', 'bb', 'cc']}) #другий дф
mrg_inner = pd.merge(df_1, df_2, on='id', how='inner') #merge inner
mrg_left = pd.merge(df_1, df_2, on='id', how='left') #merge left
mrg_right = pd.merge(df_1, df_2, on='id', how='right') #merge right
mrg_outer = pd.merge(df_1, df_2, on='id', how='outer') #merge outer
print('inner', len(mrg_inner)) #кількість рядків inner
print('left', len(mrg_left)) #кількість рядків left
print('right', len(mrg_right)) #кількість рядків right
print('outer', len(mrg_outer)) #кількість рядків outer
A = orders_copy_5[orders_copy_5['Order Year'] <= 2010] #беремо копію, де вже є поле Order Year
B = orders_copy_5[orders_copy_5['Order Year'] > 2010] #беремо копію, де вже є поле Order Year
C = pd.concat([A, B], axis=0) #об'єднання за стороками
print(len(orders_copy_5), len(C)) #перевіряємо на к-ть рядків

8399
Status
No          7527
Returned     872
Name: count, dtype: int64
['Central' 'East' 'South' 'West'] ['Nunavut' 'Northwest Territories' 'Atlantic' 'Prarie' 'West' 'Ontario'
 'Quebec' 'Yukon']
Region
Central    2
East       2
South      2
West       2
Name: count, dtype: int64
10390 8399
3982 1991
inner 1
left 3
right 3
outer 5
8399 8399

In [63]:
#Завдання 13. Бінінг, категорії та накопичувальні обчислення
maxx = orders['Sales'].max() #максимальні продажі для межі останнього інтервалу
sales_cut = pd.cut(orders['Sales'], bins=[0, 500, 2000, 10000, maxx], labels=['Low', 'Medium', 'High', 'Very High']) #ділимо дф
print(sales_cut.value_counts()) #розподіл по інтервалам
sales_cut_q = pd.cut(orders['Sales'], bins=4, labels=['Low', 'Medium', 'High', 'Very High']) #ділимо на чотири рівні за шириною інтервали
print(sales_cut_q.value_counts()) # розподіл по інтервалам
orders_copy_5['Profit_Q'] = pd.qcut(orders_copy_5['Profit'], q=4, labels=['Q1', 'Q2', 'Q3', 'Q4']) #ділимо Profit на 4 рівні інтервали
orders_copy_5[['Profit_Q', 'Sales']].groupby('Profit_Q')['Sales'].mean() #середні продажі в кожному інтервалі
orders_copy_5['Product Category'] = orders_copy_5['Product Category'].astype('category') #змінюємо тип даних на category
orders_copy_5['Region'] = orders_copy_5['Region'].astype('category') #змінюємо тип даних на category
print(orders['Product Category'].memory_usage(), orders_copy_5['Product Category'].memory_usage(),
      orders_copy_5['Product Category'].memory_usage() / orders['Product Category'].memory_usage()) #виводимо обсяг пам’яті Product Category до і після перетворення та у скільки разів він змінився
print(orders['Region'].memory_usage(), orders_copy_5['Region'].memory_usage(), orders_copy_5['Region'].memory_usage() / orders['Region'].memory_usage()) #виводимо обсяг пам’яті Region до і після перетворення та у скільки разів він змінився
orders_copy_5.sort_values('Order Date', inplace=True) #сортуємо на копії
orders_copy_5['Sales_Cumsum'] = orders_copy_5['Sales'].cumsum() #додаємо наростаючу суму продажів
print(round((orders_copy_5['Sales_Cumsum'].iloc[orders_copy_5.shape[0] - 1]), 2) == round(orders_copy_5['Sales'].sum(), 2)) #округлюємо до 2 знаків, внакше рівності не буде
roll_mean = orders_copy_rsm.rolling(3).mean() #ковзне середнє з вікном у три місяці,
exp_mean = orders_copy_rsm.expanding(1).mean() #наростаюче середнє від початку періоду
pct_change = orders_copy_rsm.pct_change() #відсоткова зміна продажів
diff = orders_copy_rsm.diff() #відсоткова зміна продажів
print(roll_mean.isna().sum(), exp_mean.isna().sum(), pct_change.isna().sum(), diff.isna().sum()) #кількість порожніх значень на початку кожного з цих рядів

Sales
Low          4370
Medium       2157
High         1580
Very High     292
Name: count, dtype: int64
Sales
Low          8359
Medium         38
High            1
Very High       1
Name: count, dtype: int64
67324 8663 0.12867625215376388
67324 8895 0.13212227437466578
True
Sales    2
dtype: int64 Sales    0
dtype: int64 Sales    1
dtype: int64 Sales    1
dtype: int64

/tmp/ipykernel_719/1305485877.py:8: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  orders_copy_5[['Profit_Q', 'Sales']].groupby('Profit_Q')['Sales'].mean() #середні продажі в кожному інтервалі

In [64]:
#Завдання 14. Ієрархічний індекс
i_indx = orders.groupby(['Region', 'Product Category', 'Product Sub-Category'])['Sales'].sum() #сума продажів за трьома рівнями одразу: Region → Product Category → Product Sub-Category
print(len(i_indx.index[0])) #кількість рівнів індексу
print(len(i_indx)) #кількість рядків результату
print(len(i_indx.xs('West'))) #дані лише регіону West
print(i_indx.swaplevel(0).sort_index()) # назви рівнів після свапу
orders_prcat_u = orders_prcat.unstack(level=0) #рівень Product Category з рядків у колонки
orders_prcat_s = orders_prcat_u.stack(level=0).swaplevel() #рівень Product Category з полів у рядки
print(orders_prcat_u.shape, orders_prcat_s.shape) #розміри обох результатів
i_indx = i_indx.reset_index() #скидання індексів
print(i_indx.memory_usage()) #розміри та назви колонок

3
135
17
Product Sub-Category          Product Category  Region
Appliances                    Office Supplies   Atlantic                 145403.1400
                                                Northwest Territories     33019.0800
                                                Nunavut                   12565.7700
                                                Ontario                  202346.8400
                                                Prarie                   111998.9000
                                                                            ...
Telephones and Communication  Technology        Ontario                  395085.1595
                                                Prarie                   367353.0255
                                                Quebec                   173498.0560
                                                West                     465265.6815
                                                Yukon                    129312.2170
Name: Sales, Length: 135, dtype: float64
(17, 3) (17,)
Index                    132
Region                  1080
Product Category        1080
Product Sub-Category    1080
Sales                   1080
dtype: int64

In [65]:
i_indx

       Region Product Category          Product Sub-Category       Sales
0    Atlantic        Furniture                     Bookcases  139521.130
1    Atlantic        Furniture            Chairs & Chairmats  197849.600
2    Atlantic        Furniture            Office Furnishings  100429.000
3    Atlantic        Furniture                        Tables  270927.052
4    Atlantic  Office Supplies                    Appliances  145403.140
..        ...              ...                           ...         ...
130     Yukon  Office Supplies        Storage & Organization   84089.270
131     Yukon       Technology          Computer Peripherals   41300.150
132     Yukon       Technology               Copiers and Fax   65251.560
133     Yukon       Technology               Office Machines  182127.210
134     Yukon       Technology  Telephones and Communication  129312.217

[135 rows x 4 columns]